// shared/ItemRegistry.js — Central item ID and category registry

export const ITEM_CATEGORIES = {
  SEED: 'seed',
  CROP: 'crop',
  ANIMAL_PRODUCT: 'animal_product',
  FISH: 'fish',
  ORE: 'ore',
  BAR: 'bar',
  PROCESSED: 'processed',
  TOOL: 'tool',
};

export const TOOLS = {
  HOE: 'hoe',
  WATERING_CAN: 'watering_can',
  PICKAXE: 'pickaxe',
  AXE: 'axe',
  FISHING_ROD: 'fishing_rod',
};

// Maps item IDs to display info
export const ITEMS = {
  // Crops
  parsnip: { name: 'Parsnip', category: 'crop' },
  potato: { name: 'Potato', category: 'crop' },
  cauliflower: { name: 'Cauliflower', category: 'crop' },
  garlic: { name: 'Garlic', category: 'crop' },
  kale: { name: 'Kale', category: 'crop' },
  strawberry: { name: 'Strawberry', category: 'crop' },
  melon: { name: 'Melon', category: 'crop' },
  tomato: { name: 'Tomato', category: 'crop' },
  blueberry: { name: 'Blueberry', category: 'crop' },
  hot_pepper: { name: 'Hot Pepper', category: 'crop' },
  corn: { name: 'Corn', category: 'crop' },
  red_cabbage: { name: 'Red Cabbage', category: 'crop' },
  pumpkin: { name: 'Pumpkin', category: 'crop' },
  cranberry: { name: 'Cranberry', category: 'crop' },
  grape: { name: 'Grape', category: 'crop' },
  artichoke: { name: 'Artichoke', category: 'crop' },
  beet: { name: 'Beet', category: 'crop' },
  yam: { name: 'Yam', category: 'crop' },
  wheat: { name: 'Wheat', category: 'crop' },
  ancient_fruit: { name: 'Ancient Fruit', category: 'crop' },
  starfruit: { name: 'Starfruit', category: 'crop' },
  coffee_bean: { name: 'Coffee Bean', category: 'crop' },
  sunflower: { name: 'Sunflower', category: 'crop' },
  carrot: { name: 'Carrot', category: 'crop' },
  // Seeds
  parsnip_seed: { name: 'Parsnip Seeds', category: 'seed' },
  potato_seed: { name: 'Potato Seeds', category: 'seed' },
  cauliflower_seed: { name: 'Cauliflower Seeds', category: 'seed' },
  garlic_seed: { name: 'Garlic Seeds', category: 'seed' },
  kale_seed: { name: 'Kale Seeds', category: 'seed' },
  strawberry_seed: { name: 'Strawberry Seeds', category: 'seed' },
  melon_seed: { name: 'Melon Seeds', category: 'seed' },
  tomato_seed: { name: 'Tomato Seeds', category: 'seed' },
  blueberry_seed: { name: 'Blueberry Seeds', category: 'seed' },
  hot_pepper_seed: { name: 'Hot Pepper Seeds', category: 'seed' },
  corn_seed: { name: 'Corn Seeds', category: 'seed' },
  red_cabbage_seed: { name: 'Red Cabbage Seeds', category: 'seed' },
  pumpkin_seed: { name: 'Pumpkin Seeds', category: 'seed' },
  cranberry_seed: { name: 'Cranberry Seeds', category: 'seed' },
  grape_seed: { name: 'Grape Seeds', category: 'seed' },
  artichoke_seed: { name: 'Artichoke Seeds', category: 'seed' },
  beet_seed: { name: 'Beet Seeds', category: 'seed' },
  yam_seed: { name: 'Yam Seeds', category: 'seed' },
  wheat_seed: { name: 'Wheat Seeds', category: 'seed' },
  ancient_fruit_seed: { name: 'Ancient Fruit Seeds', category: 'seed' },
  starfruit_seed: { name: 'Starfruit Seeds', category: 'seed' },
  coffee_bean_seed: { name: 'Coffee Bean Seeds', category: 'seed' },
  sunflower_seed: { name: 'Sunflower Seeds', category: 'seed' },
  carrot_seed: { name: 'Carrot Seeds', category: 'seed' },
  // Animal products
  egg: { name: 'Egg', category: 'animal_product' },
  milk: { name: 'Milk', category: 'animal_product' },
  wool: { name: 'Wool', category: 'animal_product' },
  cheese: { name: 'Cheese', category: 'animal_product' },
  honey: { name: 'Honey', category: 'animal_product' },
  // Ores
  copper_ore: { name: 'Copper Ore', category: 'ore' },
  iron_ore: { name: 'Iron Ore', category: 'ore' },
  gold_ore: { name: 'Gold Ore', category: 'ore' },
  // Bars
  copper_bar: { name: 'Copper Bar', category: 'bar' },
  iron_bar: { name: 'Iron Bar', category: 'bar' },
  gold_bar: { name: 'Gold Bar', category: 'bar' },
  // Processed
  flour: { name: 'Flour', category: 'processed' },
  bread: { name: 'Bread', category: 'processed' },
  cake: { name: 'Cake', category: 'processed' },
  cheese_wheel: { name: 'Cheese Wheel', category: 'processed' },
  cloth: { name: 'Cloth', category: 'processed' },
  // Tools
  hoe: { name: 'Hoe', category: 'tool' },
  watering_can: { name: 'Watering Can', category: 'tool' },
  pickaxe: { name: 'Pickaxe', category: 'tool' },
  axe: { name: 'Axe', category: 'tool' },
  fishing_rod: { name: 'Fishing Rod', category: 'tool' },
};
